///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppLoadPointValue {
/*
{
  "switch": true,
  "notice": "这是app首屏加载广告"
} 
*/

  bool? theSwitch;
  String? notice;

  AppLoadPointValue({
    this.theSwitch,
    this.notice,
  });
  AppLoadPointValue.fromJson(Map<String, dynamic> json) {
    theSwitch = json["switch"];
    notice = json["notice"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["switch"] = theSwitch;
    data["notice"] = notice;
    return data;
  }
}

class AppLoadPoint {
/*
{
  "code": 200,
  "text": "操作成功！",
  "value": {
    "switch": true,
    "notice": "这是app首屏加载广告"
  }
} 
*/

  int? code;
  String? text;
  AppLoadPointValue? value;

  AppLoadPoint({
    this.code,
    this.text,
    this.value,
  });
  AppLoadPoint.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    text = json["text"]?.toString();
    value = (json["value"] != null)
        ? AppLoadPointValue.fromJson(json["value"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["text"] = text;
    if (value != null) {
      data["value"] = value!.toJson();
    }
    return data;
  }
}
