///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppAuthUpgradeValue {
/*
{
  "upgrade": false,
  "download": "",
  "dialog": "这是app首屏加载广告"
} 
*/

  bool? upgrade;
  String? download;
  String? dialog;

  AppAuthUpgradeValue({
    this.upgrade,
    this.download,
    this.dialog,
  });
  AppAuthUpgradeValue.fromJson(Map<String, dynamic> json) {
    upgrade = json["upgrade"];
    download = json["download"]?.toString();
    dialog = json["dialog"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["upgrade"] = upgrade;
    data["download"] = download;
    data["dialog"] = dialog;
    return data;
  }
}

class AppAuthUpgrade {
/*
{
  "code": 200,
  "text": "操作成功！",
  "value": {
    "upgrade": false,
    "download": "",
    "dialog": "这是app首屏加载广告"
  }
} 
*/

  int? code;
  String? text;
  AppAuthUpgradeValue? value;

  AppAuthUpgrade({
    this.code,
    this.text,
    this.value,
  });
  AppAuthUpgrade.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    text = json["text"]?.toString();
    value = (json["value"] != null)
        ? AppAuthUpgradeValue.fromJson(json["value"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["text"] = text;
    if (value != null) {
      data["value"] = value!.toJson();
    }
    return data;
  }
}
