///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: camel_case_types, non_constant_identifier_names

class getSearchDatasValueSearchResultListVideoType {
/*
{
  "_id": "603559b98de8ff1713136e0c",
  "name": "综艺"
} 
*/

  String? Id;
  String? name;

  getSearchDatasValueSearchResultListVideoType({
    this.Id,
    this.name,
  });
  getSearchDatasValueSearchResultListVideoType.fromJson(
      Map<String, dynamic> json) {
    Id = json["_id"]?.toString();
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["_id"] = Id;
    data["name"] = name;
    return data;
  }
}

class getSearchDatasValueSearchResultList {
/*
{
  "_id": "60929f6be38c3f16000427dc",
  "videoTitle": "姐姐，听我说",
  "director": "未知",
  "videoImage": "https://p.ssl.qhimg.com/d/dy_c44518bf24c8698566fb03e7d14e80c1.jpg",
  "poster": "",
  "performer": "未知",
  "video_type": {
    "_id": "603559b98de8ff1713136e0c",
    "name": "综艺"
  },
  "video_rate": 0,
  "update_time": "2021-04-22 11:26:26",
  "language": "国语",
  "sub_region": "大陆",
  "rel_time": "2021",
  "introduce": "请到同语言类节目《奇葩说》艺人以男性视角来为《听姐说》补充观点，延续语言类节目的思辨风格，以开杠辩论的快节奏方式输出观点，用多元视角补充原生节目每期的话题点，从而进一步引发观众共情和思考。",
  "remind_tip": "更新至2021-04-16期",
  "popular": false,
  "allow_reply": false,
  "display": true,
  "scource_sort": false
} 
*/

  String? Id;
  String? videoTitle;
  String? director;
  String? videoImage;
  String? poster;
  String? performer;
  getSearchDatasValueSearchResultListVideoType? videoType;
  int? videoRate;
  String? updateTime;
  String? language;
  String? subRegion;
  String? relTime;
  String? introduce;
  String? remindTip;
  bool? popular;
  bool? allowReply;
  bool? display;
  bool? scourceSort;

  getSearchDatasValueSearchResultList({
    this.Id,
    this.videoTitle,
    this.director,
    this.videoImage,
    this.poster,
    this.performer,
    this.videoType,
    this.videoRate,
    this.updateTime,
    this.language,
    this.subRegion,
    this.relTime,
    this.introduce,
    this.remindTip,
    this.popular,
    this.allowReply,
    this.display,
    this.scourceSort,
  });
  getSearchDatasValueSearchResultList.fromJson(Map<String, dynamic> json) {
    Id = json["_id"]?.toString();
    videoTitle = json["videoTitle"]?.toString();
    director = json["director"]?.toString();
    videoImage = json["videoImage"]?.toString();
    poster = json["poster"]?.toString();
    performer = json["performer"]?.toString();
    videoType = (json["video_type"] != null)
        ? getSearchDatasValueSearchResultListVideoType
            .fromJson(json["video_type"])
        : null;
    videoRate = json["video_rate"]?.toInt();
    updateTime = json["update_time"]?.toString();
    language = json["language"]?.toString();
    subRegion = json["sub_region"]?.toString();
    relTime = json["rel_time"]?.toString();
    introduce = json["introduce"]?.toString();
    remindTip = json["remind_tip"]?.toString();
    popular = json["popular"];
    allowReply = json["allow_reply"];
    display = json["display"];
    scourceSort = json["scource_sort"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["_id"] = Id;
    data["videoTitle"] = videoTitle;
    data["director"] = director;
    data["videoImage"] = videoImage;
    data["poster"] = poster;
    data["performer"] = performer;
    if (videoType != null) {
      data["video_type"] = videoType!.toJson();
    }
    data["video_rate"] = videoRate;
    data["update_time"] = updateTime;
    data["language"] = language;
    data["sub_region"] = subRegion;
    data["rel_time"] = relTime;
    data["introduce"] = introduce;
    data["remind_tip"] = remindTip;
    data["popular"] = popular;
    data["allow_reply"] = allowReply;
    data["display"] = display;
    data["scource_sort"] = scourceSort;
    return data;
  }
}

class getSearchDatasValueSearchResult {
/*
{
  "page": 1,
  "total": 1194,
  "list": [
    {
      "_id": "60929f6be38c3f16000427dc",
      "videoTitle": "姐姐，听我说",
      "director": "未知",
      "videoImage": "https://p.ssl.qhimg.com/d/dy_c44518bf24c8698566fb03e7d14e80c1.jpg",
      "poster": "",
      "performer": "未知",
      "video_type": {
        "_id": "603559b98de8ff1713136e0c",
        "name": "综艺"
      },
      "video_rate": 0,
      "update_time": "2021-04-22 11:26:26",
      "language": "国语",
      "sub_region": "大陆",
      "rel_time": "2021",
      "introduce": "请到同语言类节目《奇葩说》艺人以男性视角来为《听姐说》补充观点，延续语言类节目的思辨风格，以开杠辩论的快节奏方式输出观点，用多元视角补充原生节目每期的话题点，从而进一步引发观众共情和思考。",
      "remind_tip": "更新至2021-04-16期",
      "popular": false,
      "allow_reply": false,
      "display": true,
      "scource_sort": false
    }
  ]
} 
*/

  int? page;
  int? total;
  List<getSearchDatasValueSearchResultList?>? list;

  getSearchDatasValueSearchResult({
    this.page,
    this.total,
    this.list,
  });
  getSearchDatasValueSearchResult.fromJson(Map<String, dynamic> json) {
    page = json["page"]?.toInt();
    total = json["total"]?.toInt();
    if (json["list"] != null) {
      final v = json["list"];
      final arr0 = <getSearchDatasValueSearchResultList>[];
      v.forEach((v) {
        arr0.add(getSearchDatasValueSearchResultList.fromJson(v));
      });
      list = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["page"] = page;
    data["total"] = total;
    if (list != null) {
      final v = list;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["list"] = arr0;
    }
    return data;
  }
}

class getSearchDatasValue {
/*
{
  "searchName": "我",
  "searchResult": {
    "page": 1,
    "total": 1194,
    "list": [
      {
        "_id": "60929f6be38c3f16000427dc",
        "videoTitle": "姐姐，听我说",
        "director": "未知",
        "videoImage": "https://p.ssl.qhimg.com/d/dy_c44518bf24c8698566fb03e7d14e80c1.jpg",
        "poster": "",
        "performer": "未知",
        "video_type": {
          "_id": "603559b98de8ff1713136e0c",
          "name": "综艺"
        },
        "video_rate": 0,
        "update_time": "2021-04-22 11:26:26",
        "language": "国语",
        "sub_region": "大陆",
        "rel_time": "2021",
        "introduce": "请到同语言类节目《奇葩说》艺人以男性视角来为《听姐说》补充观点，延续语言类节目的思辨风格，以开杠辩论的快节奏方式输出观点，用多元视角补充原生节目每期的话题点，从而进一步引发观众共情和思考。",
        "remind_tip": "更新至2021-04-16期",
        "popular": false,
        "allow_reply": false,
        "display": true,
        "scource_sort": false
      }
    ]
  }
} 
*/

  String? searchName;
  getSearchDatasValueSearchResult? searchResult;

  getSearchDatasValue({
    this.searchName,
    this.searchResult,
  });
  getSearchDatasValue.fromJson(Map<String, dynamic> json) {
    searchName = json["searchName"]?.toString();
    searchResult = (json["searchResult"] != null)
        ? getSearchDatasValueSearchResult.fromJson(json["searchResult"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["searchName"] = searchName;
    if (searchResult != null) {
      data["searchResult"] = searchResult!.toJson();
    }
    return data;
  }
}

class getSearchDatas {
/*
{
  "code": 200,
  "text": "操作成功！",
  "value": {
    "searchName": "我",
    "searchResult": {
      "page": 1,
      "total": 1194,
      "list": [
        {
          "_id": "60929f6be38c3f16000427dc",
          "videoTitle": "姐姐，听我说",
          "director": "未知",
          "videoImage": "https://p.ssl.qhimg.com/d/dy_c44518bf24c8698566fb03e7d14e80c1.jpg",
          "poster": "",
          "performer": "未知",
          "video_type": {
            "_id": "603559b98de8ff1713136e0c",
            "name": "综艺"
          },
          "video_rate": 0,
          "update_time": "2021-04-22 11:26:26",
          "language": "国语",
          "sub_region": "大陆",
          "rel_time": "2021",
          "introduce": "请到同语言类节目《奇葩说》艺人以男性视角来为《听姐说》补充观点，延续语言类节目的思辨风格，以开杠辩论的快节奏方式输出观点，用多元视角补充原生节目每期的话题点，从而进一步引发观众共情和思考。",
          "remind_tip": "更新至2021-04-16期",
          "popular": false,
          "allow_reply": false,
          "display": true,
          "scource_sort": false
        }
      ]
    }
  }
} 
*/

  int? code;
  String? text;
  getSearchDatasValue? value;

  getSearchDatas({
    this.code,
    this.text,
    this.value,
  });
  getSearchDatas.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    text = json["text"]?.toString();
    value = (json["value"] != null)
        ? getSearchDatasValue.fromJson(json["value"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["text"] = text;
    if (value != null) {
      data["value"] = value!.toJson();
    }
    return data;
  }
}
