///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetTypeListValue {
/*
{
  "_id": "0",
  "name": "首页",
  "active": true,
  "link": "/"
} 
*/

  String? Id;
  String? name;
  bool? active;
  String? link;

  GetTypeListValue({
    this.Id,
    this.name,
    this.active,
    this.link,
  });
  GetTypeListValue.fromJson(Map<String, dynamic> json) {
    Id = json["_id"]?.toString();
    name = json["name"]?.toString();
    active = json["active"];
    link = json["link"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["_id"] = Id;
    data["name"] = name;
    data["active"] = active;
    data["link"] = link;
    return data;
  }
}

class GetTypeList {
/*
{
  "code": 200,
  "text": "操作成功！",
  "value": [
    {
      "_id": "0",
      "name": "首页",
      "active": true,
      "link": "/"
    }
  ]
} 
*/

  int? code;
  String? text;
  List<GetTypeListValue?>? value;

  GetTypeList({
    this.code,
    this.text,
    this.value,
  });
  GetTypeList.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    text = json["text"]?.toString();
    if (json["value"] != null) {
      final v = json["value"];
      final arr0 = <GetTypeListValue>[];
      v.forEach((v) {
        arr0.add(GetTypeListValue.fromJson(v));
      });
      value = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["text"] = text;
    if (value != null) {
      final v = value;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["value"] = arr0;
    }
    return data;
  }
}
